blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://halotukozak.github.io/alpaca/
    about: Read the full documentation
  - name: ðŸ’¬ Discussions
    url: https://github.com/halotukozak/alpaca/discussions
    about: Ask questions and discuss ideas with the community
